export const LIMITS = {
  MESSAGE_MAX_CHARS: 1000,
  MESSAGE_WARN_CHARS: 900,
  SESSION_MAX_MESSAGES: 50,
  SESSION_WARN_MESSAGES: 45,
  DAILY_MAX_MESSAGES: 30,
  DAILY_WARN_MESSAGES: 25,
  MESSAGE_COOLDOWN_MS: 3000,
  MAX_ACTIVE_BLOCKS: 10,
} as const;
